### ISSUE TITLE
Multiple worksheet and formula on cell

### ISSUE THREAD

**Issue by udaydutta** [jsegarra1971/MyExcel#1]
This is an awesome client-side library. Much more simpler than js-xlsx.  However, could you please give some sample code for creating multiple worksheet and also how to define formula on the cell?

**Comment by josesegarra** [comment]
To add a sheet:

    excel.addSheet("Sheet 2");
To edit a sheet

	excel.set( {sheet:0,value:"This is Sheet 1" } );
There is no support for removing sheets. About formulas see issue #2
