### ISSUE TITLE
Unable to upload file to SharePoint/Server

### ISSUE THREAD

**Issue by BM4291** [jsegarra1971/MyExcel#10]
Hi,

Excellent plug-in which has proven to be incredibly helpful for achieving a great deal of efficiency gain for a project I'm working on.

Generate works great and I can open the file locally but I can't seem to send the file to a SharePoint location; when I've tried using the excel object, it saves the file but returns a corrupted document with 0kb size.

I've tried playing with the code to force it to export as a blob but having no luck... Any ideas?

I'm using a POST REST operation which works fine with JSPDF and it's pdf.output('blob') function:

```javascript
function addFileToDocumentLibrary(siteURL, folder, file, fileName, successCallback, failureCallback){
    var url = siteURL + '/_api/web/GetFolderByServerRelativeUrl(\'' + folder + '\')/files/add(url=\'' + fileName + '\', overwrite=true)';

    $.ajax({
        url: url,
        type: 'POST',
        data: file,
        processData: false,
        headers: {
            'accept': 'application/json; odata=verbose',
            'X-RequestDigest': $('#__REQUESTDIGEST').val()
            //'content-length': arrayBuffer.byteLength
        },
        success: function(data){
            successCallback(data)
        },
        error: function(xhr, ajaxOptions, thrownError){
            failureCallback(xhr, ajaxOptions, thrownError)
        }
    });
}
```

**Comment by josesegarra** [comment]
Sorry. I am not a SharePoint expert. Check the HTTP headers with the jsPDF file and see what is different with Excel this will give you a hint as to what they behave differently.

On the MyExcel code...it already exports a blob, I would try:

Forcing a mime-type, by in the last line:

`zip.generateAsync({ type: "blob",mimeType:"application/vnd.ms-excel" })
`
Or changing the "blob" to "unit8array", in the same line:

`{type: "uint8array"}`

Good luck

**Comment by BM4291** [comment]
Thanks, I will give that a try; the issue I seem to have is returning a blob as the excel variable itself just returns an object. 

```excel.generate()``` whilst producing an Excel file doesn't then expose or create anything I can use to upload the file itself:

i.e. if I do something like ```file = excel.generate(fileName)``` I get the excel object

I've checked the code for jsPDF and what you're suggesting is quite similar:

```file = pdf.output('blob')``` returns a blob that I can use for upload.

I'll set up a separate function and use what you've suggested and keep at it, just a case of testing the different conditions.

**Update - Got it working but feels quite hacky at best!
I've added an additional line after 642: ```uploadFile(content)``` and then made a very simple function in my project:
```javascript
function uploadFile(file){
    addFileToDocumentLibrary(siteURL, folderName, file, fileName, attachmentSuccess, attachmentFailure);
}
```
This obviously won't work for all users but the best I can think of for now... Anything you'd do differently/that would be more generalised?

**Comment by josesegarra** [comment]
Right now, the generate function does two things; generate excel and download and returns nothing. I think that making it return the EXCEL object and making download optional (via input parameter) would suit your needs, don´t break anything and be generic enough.

Feel free to implement it, and I will add to the trunk, or I´ll do it (might take a while though).

Thanks !!

**Comment by BM4291** [comment]
Sure, will give it a try and see what I can do...!
