### ISSUE TITLE
.zip file extension when opening in Excel

### ISSUE THREAD

**Issue by staplCris** [jsegarra1971/MyExcel#11]
When doing the following...

excel.generate("MySpreadsheet.xlsx");

and then the dialog box pops up,

![image](https://user-images.githubusercontent.com/39803532/40790794-7ba9abc0-64bb-11e8-8f58-b9c5c7d81f96.png)

the filename appears to be correct ( MySpreadsheet.xlsx)

But, if user chooses to Open with Excel, the spreadsheet name has .zip appended to it.  
(example:   MySpreadsheet.xlsx.zip )

![image](https://user-images.githubusercontent.com/39803532/40791653-a3538518-64bd-11e8-8611-526a758b42ac.png)

If I choose to save the file instead of opening in Excel the file name does not have .zip appended.

This behavior is also manifested in the MyExcel sample provided here...
http://jsegarra1971.github.io/MyExcel/sample.html

Is this a feature?  How does one prevent the .zip file extension when opening in Excel instead of saving.

**Comment by josesegarra** [comment]
Hi, this is a known issue with Firefox doing content sniffing [https://github.com/eligrey/FileSaver.js/issues/139](https://github.com/eligrey/FileSaver.js/issues/139).  You can fix it by registering the xlsx extension with the `application/vnd.ms-excel mime-type`.

In any case, I have updated the sample to include the mime-type. Please try [http://jsegarra1971.github.io/MyExcel/sample.html](http://jsegarra1971.github.io/MyExcel/sample.html)  and if it works I will update the code.

Regards,

**Comment by staplCris** [comment]
Works.  Thanks for the quick response and the explanation.

**Comment by josesegarra** [comment]
Updated master branch with the mimetype. Thanks!!
