### ISSUE TITLE
Not support String format 

### ISSUE THREAD

**Issue by rajeshsoft** [jsegarra1971/MyExcel#14]
Not supporting string for MAC.

**Comment by josesegarra** [comment]
Could you be more specific ??

**Comment by rajeshsoft** [comment]
I have run the sample program for MAC OS but not showing string contents in the XLs file. I have attached XLs file. You have open only MAC OS because XLS working in other windows and Linux OS.
[SampleData (47).xlsx](https://github.com/jsegarra1971/MyExcel/files/2182854/SampleData.47.xlsx)

**Comment by ErikvdBurgwal** [comment]
@rajeshsoft Could you be more specific about the application (& version) you are using on the Mac to open the .xlsx-document?

**Comment by rajeshsoft** [comment]
@ErikvdBurgwal , I have used Numbers (spreadsheet) application latest version in MacBook pro (10.12.6) OS.

**Comment by ErikvdBurgwal** [comment]
It looks like Numbers does not support the direct-text storage used by MyExcel. Although it is more a Numbers-problem than a MyExcel bug, it would be good to implement the dictionary-approach that is more common for texts (as it potentially saves size & improves performance on large sheets).

**Comment by josesegarra** [comment]
Closing the issue...
