### ISSUE TITLE
Merge Cell

### ISSUE THREAD

**Issue by dodomui** [jsegarra1971/MyExcel#20]
Hi, May I ask how could I merge cell?
Thanks.

Tried excel.set(0,7,3,"15+13", '', 2); but doesn't work.

**Comment by dodomui** [comment]
Make it work by edit myexcel.js excel.set function

`excel.set = function (s, column, row, value, style, colspan) {
            if (isObject(s)) return this.set(s.sheet, s.column, s.row, s.value, s.style);                                        // If using Object form, expand it
            if (!s) s = 0;                                                                                                       // Use default sheet
            s = sheets.get(s);
            if (isNaN(column) && isNaN(row)) return s.set(value, style);                                                         // If this is a sheet operation
            if (!isNaN(column)) {                                                                                                // If this is a column operation
                if (!isNaN(row)) {
                    var isstring = style && styles.getStyle(style-1).isstring;
                    return setCell(s.getCell(column, row), value, style, isstring, colspan);                                              // and also a ROW operation the this is a CELL operation
                }
                return setColumn(s.getColumn(column), value, style);                                                             // if not we confirm than this is a COLUMN operation
            }
            return setRow(s.getRow(row), value, style);                                                                          // If got here, thet this is a Row operation
        }`

**Comment by dodomui** [comment]
return setCell(s.getCell(column, row), value, style, isstring, colspan);

**Comment by marcusy3k** [comment]
I suggest you to be one of the contributor ^_^

**Comment by josesegarra** [comment]
Support for cell merging was included a couple of weeks ago by Gabriel. See https://github.com/jsegarra1971/MyExcel/pull/16

**Comment by marcusy3k** [comment]
oh, thanks.

**Comment by dodomui** [comment]
Ya, the merge function is already there.
But it doesn't work in my case... so i make some modification, not sure did I miss anything...
