### ISSUE TITLE
merge cells

### ISSUE THREAD

**Issue by cirabad117** [jsegarra1971/MyExcel#22]
Is there an option to merge cells in a sheet?

**Comment by dodomui** [comment]
Actually there's merge cells option.
https://github.com/jsegarra1971/MyExcel/pull/16
But in my case it doesn't work so i make some modification.

return setCell(s.getCell(column, row), value, style, isstring, colspan);

**Comment by dodomui** [comment]
excel.set(0,7,3,"15+13", style, 2);
2 = merge 2 cells

**Comment by cirabad117** [comment]
Yeah, I used that too, It is not the expected behavior that I thought but it's OK. Now the problem that I can't set the text inside a cell. My text look like this:
![captura](https://user-images.githubusercontent.com/33065606/43910575-cc846fec-9bc2-11e8-94ef-50ecb0b0144c.PNG)

**Comment by cirabad117** [comment]
Yeah, I used too. I suppose this is the only way to make it until someone add moro code, Thanks anyway
