### ISSUE TITLE
Issue in .ts file

### ISSUE THREAD

**Issue by kkbalu** [jsegarra1971/MyExcel#24]
Cannot find name '$JExcel'. Did you mean 'excel'? .  when we build in angular6, it thrown errors like this. Can you guide how to overcome this issue

**Comment by josesegarra** [comment]
This is a pure JS library. You are welcomed to create wrappers to specific frameworks. https://itnext.io/how-i-wrapped-ngtagify-a-pure-js-lib-into-an-angular-module-packed-and-installed-it-on-my-app-ac828e89fdf0
