### ISSUE TITLE
Previous Drag and drop file upload is not working with jszip.js 3.0 version.

### ISSUE THREAD

**Issue by udaydutta** [jsegarra1971/MyExcel#3]
Jose - Thank you for your reply. I have used the cell formula. It is
working fine but after opening the downloaded Excel file I must click on
the cell in order to formula  get effected.

I am facing another problem with your version o

[xlsx.js.txt](https://github.com/jsegarra1971/MyExcel/files/1187654/xlsx.js.txt)

[xlsx.js.txt](https://github.com/jsegarra1971/MyExcel/files/1187655/xlsx.js.txt)

f jszip.js *file. I already
have a code for file (.xlsx) drag & drop using jszip.js. Please see the
attached two files containing my code example. Could you please let me know
what change I need to make to*"xlsx.js*"  in order to it work. In that case
I  can use single jszip.js file for both .XLSX file creation and .XLSX file
parsing. I am also attaching the version of jszip.js i was using.

Thank you. I will be highly appreciate your help.

UCD

**Comment by josesegarra** [comment]
The two files you sent are the same, both look like the code from http://sheetjs.com. Also it is not clear to me from your text what is not working in your application.

**Comment by udaydutta** [comment]
Jose - Good Morning! Thank you for your reply. I apologize for not giving you enough clarification for my question.  I am trying to explain it again with few more details. 

1. In one my application I used  uploading .xlsx file to web page (By file drag and drop) and after parsing file, the data are displayed into a html table.  I used the .xlsx file reading/parsing code from https://github.com/SheetJS/js-xlsx site. The two javascript files from that site, I am using in  my sample web page (dragndropTest.html)  are below.

    a. jszip.js
    b. xlsx.js

In your Excel creation code , you are  also using jszip.js (v3.1.3)  file. Therefore,  I tried your version of jszip.js file in my code dragndropTest.html.  that is not working.  I request your help if you can give me some clue how I make jszip.js (v3.1.3) work with my code dragndropTest.html.  In that case I  will able to use same jszip.js file for both .xlsx file parsing as well as .xlsx file creation. I am attaching  the following three files to run my test code. 

a. dragndropTest.html - My test web page.
b. jszip.js - The version of file downloaded from https://github.com/SheetJS/js-xlsx..  My code dragndropTest.html works with this file.  There is a difference in code between this jszip.js file and the jszip.js (v3.1.3) file that your code uses.
c, xlsx.js - Javascript code used to parse the .xlsx file that is also downloaded from https://github.com/SheetJS/js-xlsx.  

Note: I renamed the javascript files as .txt files before attaching to this mail. 


I hope, I am able clarify my question better this time. Please let me know if you need fore details.  Thank you.

UCD

[jszip.js.txt](https://github.com/jsegarra1971/MyExcel/files/1190865/jszip.js.txt)
[xlsx.js.txt](https://github.com/jsegarra1971/MyExcel/files/1190864/xlsx.js.txt)
[dragndropTest.html.txt](https://github.com/jsegarra1971/MyExcel/files/1190872/dragndropTest.html.txt)

**Comment by udaydutta** [comment]
Jose - I just forgot to ask you another question. Is it possible to use image or charts during Excel file creation using your code?  Thanks.

**Comment by josesegarra** [comment]
Your code is using a JSZip version from 2014. This version does not support async streaming. To use MyExcel with this version replace the Async generation function for the Sync version, so instead of: 

    zip.generateAsync({ type: "blob" }).then(function (content) { saveAs(content, filename); });        

Use:

    var content=zip.generate({ type: "blob" });
    saveAs(content, filename);
 
I am enclosing a ZIP file with the change. However I would recommend doing the opposite, updating your code to use the latest JSZIP version. Bear in mind that JSZIP is well supported, and if you stuck with and old version you will loose three years of patching and refactoring.

About your other question, no there is no support for charts or images. This is a simple library !!!

Kind regards, 

[TryThis.zip.txt](https://github.com/jsegarra1971/MyExcel/files/1195166/TryThis.zip.txt)
