### ISSUE TITLE
Request for you add the license text in myexcel.js file

### ISSUE THREAD

**Issue by rkg10** [jsegarra1971/MyExcel#32]
Hello Jose
I want to use your library but for I need license text in myexcel.js file to support that code is free to use.
Are you able to add license text at the top of the myexcel.js file?, that will comply the requirement in my company to use the library.
Thanks in advance.

**Comment by josesegarra** [comment]
Hi,

Sorry for the late answer. Added license text. Out of curiosity I'd appreciate if you let me know in what product it will be used. 

Regards

J
