### ISSUE TITLE
Exporting xslx file prompting error in MSOffice Excel v14 when opening

### ISSUE THREAD

**Issue by ndantonio** [jsegarra1971/MyExcel#39]
Hello,

I am exporting an excel file as a blank template with only one header "Username" on column A. 
![image](https://user-images.githubusercontent.com/20949522/125878590-6b27eedf-bac5-4375-ac29-41992de78132.png)

The problem is that upon opening on Excel, it prompts a dialog box and I dont have idea what causing the issue:
![image_2021_07_09T04_10_44_511Z](https://user-images.githubusercontent.com/20949522/125878643-900ab787-b1b3-4191-a614-ed048fca4a0e.png)

Try to replicate this on this environment:
Windows 7 Enterprise
Excel version: 14

I am using the myexcel library on our Angular application.

Thanks for the help!

**Comment by josesegarra** [comment]
I don't have your Excel version, so I can't test. I have tested with 

![image](https://user-images.githubusercontent.com/7486477/125946327-5d8823f6-640b-46ba-943a-d9042ff1a2c8.png)

OpenOffice and LibreOffice. 

The file you describe https://jsegarra.tk/MyExcel/g2.html works fine for me. 

I suggest DIFFIng a workable file in Excel Enterprise 14 with the one the library provides.

**Comment by ndantonio** [comment]
Hi @josesegarra ,

> I suggest DIFFIng a workable file in Excel Enterprise 14 with the one the library provides.

What do you mean by this and how to do it?

**Comment by josesegarra** [comment]
Create the minimum file in your Excel. Create the same one using MyExcel. Unzip both files in two separate directories, and compare the DIFFerences, you'll need to go folder by folder and file by file. 

By the way, does the sample at https://jsegarra.tk/MyExcel/g2.html also give a message?

**Comment by ndantonio** [comment]
Hi @josesegarra 

> By the way, does the sample at https://jsegarra.tk/MyExcel/g2.html also give a message?

This one works. I really can't see where the error is.

By the way, I applied the library on my Angular app. Here is my function with excel.set inside:

```
        const setCell = (
            sheetIndex?: any,
            columnIndex?: number,
            rowIndex?: number,
            cellValue?: string,
            style?: object,
            colspan?: number
        ): void => {
            const defaultStyle = { align: 'L', format: '@', isstring: true };
            const styles =
                style != undefined
                    ? excel.addStyle({ ...defaultStyle, ...style })
                    : excel.addStyle(defaultStyle);

            excel.set(
                sheetIndex,
                columnIndex,
                rowIndex,
                cellValue,
                styles,
                colspan
            );
        };
```
And here is how I use and generate it:

```
        if (data || data.length) {
            data.map((row, i) => {
                Object.values(row).map((rd, j) => {
                    const value =
                        rd['value'] == null ? '' : rd['value'].toString();
                    setCell(0, j, headerLastRow + i + 1, value, rd['style']);
                });
            });
        }
        
        excel.generate(fileName + fileExt);
```

But since it's just a template file, only header is there and no data should be added on rows.

Thank you.

**Comment by ndantonio** [comment]
[pmg_player_list.zip](https://github.com/josesegarra/MyExcel/files/6837097/pmg_player_list.zip)
Here is the sample generated file.
