### ISSUE TITLE
Need to strikethrough text in excel cell

### ISSUE THREAD

**Issue by vihars711** [jsegarra1971/MyExcel#41]
I need to strikethrough some text in a cell what is the best way to do ???? 
Thank you in advance

**Comment by josesegarra** [comment]
I have updated the font formatting options to: 
- S -> strike
- B -> bold
- I -> italic
- U -> underline

`excel.set(0,5,0,"Strike and Bold text",excel.addStyle ({font: "Calibri 12 BS"}));		// Text in BOLD and STRIKE`

regards

**Comment by vihars711** [comment]
Thank you so much @josesegarra for your quick help :)
