### ISSUE TITLE
Text format issue

### ISSUE THREAD

**Issue by vihars711** [jsegarra1971/MyExcel#42]
Hi @josesegarra,

   var stringFormatCell = excel.addStyle({
                font: "Calibri 11 #000000",
                align: "L",
                format: "@"
            });

I am using  excel.set(0, 4, 5, "2E169", stringFormatCell);

but when its export in the excel its showing me " 2E+169".

![image](https://user-images.githubusercontent.com/95840676/163118947-0a2b7c30-90b6-453b-abb6-5f532b09941d.png)

Can you please check and let me know the workaround

Thank you in advance.

**Comment by josesegarra** [comment]
Hi,

2E169 is a valid number in JavaScript. I have added support for formulas to the library, so you can use a formula instead of a number expression, for example:

			excel.set(0,1,4,'=CONCATENATE("2E169","")');
			excel.set(0,1,5,'="2E169"');

You can find a sample at http://jsegarra.net/MyExcel/sample.html#

J
