### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by W0ffie** [jsegarra1971/MyExcel#5]
It would be great if you could also select text wrapping in the formatting for a cell.

A possiblity would be to extend the align option to three characters - Horizontal, Vertical, Wrap
excel.set(0,2,undefined, 80, excel.addStyle( {align:"L T W"}));
(since it is in the <alignment> tag in the excel xml)

This can be achieved by updating the "align" array to add "wrapText"
```
var align = {
        L: "left", C: "center", R: "right", T: "top", B: "bottom", W: "wrapText"
}
```

Updating toStyleXML(style) to begin as 
```
function toStyleXml(style) {
        var alignXml = "";
        if (style.align) {
            var h = align[style.align.charAt(0)];
            var v = align[style.align.charAt(1)];
	    var w = align[style.align.charAt(2)];
            if (h || v || w) {
                alignXml = "<alignment ";
                if (h) alignXml = alignXml + ' horizontal="' + h + '" ';
                if (v) alignXml = alignXml + ' vertical="' + v + '" ';
				if (w) alignXml = alignXml + ' ' + w + '="1" ';
                alignXml = alignXml + " />";
            }
        }
.
.
.
```

And then update the normalizeAlign to
```
function normalizeAlign(a) {
        if (!a) return "---";
        var a = replaceAllMultiple(a.toString() + " - - -", "  ", " ").trim().toUpperCase().split(" ");
        return a[0].charAt(0) + a[1].charAt(0)  + a[2].charAt(0);
    }
```

Oh, it is an awesome library - really impressive.

**Comment by hookedupjoe** [comment]
Thank you @W0ffie for the great code updates to support word wrapping.    I just added a pull request with your changes to help others.   Of course thanks to @jsegarra1971 for creating this nice library.

**Comment by josesegarra** [comment]
Merged into main branch. Thanks to all !!
