### ISSUE TITLE
Can't export multi page table

### ISSUE THREAD

**Issue by varundutt2002** [jsegarra1971/MyExcel#6]
Hi jsegarra1971,

I have a table created using Datatables (Datatables.net) with pagination option. So it have multiple pages when number of rows exceed to the defined value. When I tried to export this table with your library, it's exporting only the first page and not the whole table.

Could you please help me in getting this done ?

I must appreciate the work you have done. Really great library to export HTML tables to excel in a easy way. Thank you for your great work to the community.

Thanks and regards,
Varun Dutta

**Comment by josesegarra** [comment]
Hi,

Use `excel.addSheet("Your sheet name")` to add additional sheets to the result. When writing data, you always specify the destination sheet. Notice that Sheet number 0 is created by default

```
excel.addSheet("This is sheet 1")
excel.addSheet("This is sheet 2")
excel.set(0,0,0,"Sheet 0 Cell 0 0");													 
excel.set(1,0,0,"Sheet 1 Cell 0 0");													 
excel.set(2,0,0,"Sheet 2 Cell 0 0");													
excel.set(3,0,0,"Sheet 3 Cell 0 0"); --> This gives an error, as sheet 3 has not been created

```
