### ISSUE TITLE
break line inside one cell?

### ISSUE THREAD

**Issue by Saulo** [jsegarra1971/MyExcel#9]
Hello.

How can i break line inside one cell?  i try \r\n, char(10), ...  And nothing works. :(

Or, another way to help me, is... Can i merge 3 cells in 1? How?

thanks!

**Comment by josesegarra** [comment]
Cells merging is not supported. 

For line breaks, W0ffie (big thanks) comitted code for wrapping text, it might be what you need. If not feel free to fix it.

Regards,

J
